# Generated by Django 5.1.6 on 2025-12-01 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dropout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropouts', to='teacher.teacherprofile')),
            ],
            options={
                'ordering': ['-date', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_lrn', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Drop-off', 'Drop-off'), ('Pick-up', 'Pick-up'), ('Dropped Out', 'Dropped Out')], default='Present', max_length=20)),
                ('qr_code_data', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.CharField(blank=True, choices=[('AM', 'Morning'), ('PM', 'Afternoon')], max_length=2, null=True)),
                ('transaction_type', models.CharField(choices=[('attendance', 'Attendance'), ('drop-off', 'Drop-off'), ('pick-up', 'Pick-up')], default='attendance', help_text='Type of transaction: regular attendance, drop-off, or pick-up', max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='teacher.teacherprofile')),
            ],
            options={
                'ordering': ['-date', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='teacher.teacherprofile')),
            ],
            options={
                'ordering': ['-date', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UnauthorizedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('age', models.IntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('photo', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unauthorized_persons', to='teacher.teacherprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
