# Generated by Django 5.1.6 on 2025-12-18 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('photo', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_photos', to='teacher.teacherprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
