# Generated by Django 5.1.6 on 2025-12-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_alter_parentguardian_address_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentguardian',
            name='avatar_base64',
            field=models.TextField(blank=True, default=''),
        ),
    ]
