# Generated by Django 5.1.6 on 2025-12-01 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('student_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, help_text='Guardian photo', null=True, upload_to='guardian_photos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('allowed', 'Allowed'), ('declined', 'Declined')], default='pending', help_text='Approval status of the guardian', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parent_guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_guardians', to='parents.parentguardian')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='parents.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='teacher.teacherprofile')),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
                'ordering': ['-timestamp'],
            },
        ),
    ]
