# Generated by Django 5.1.6 on 2025-12-18 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0001_initial'),
        ('parents', '0002_alter_parentguardian_address_passwordresettoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guardian',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='guardian',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='parent_guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parents.parentguardian'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('allowed', 'Allowed'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parents.student'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='student_name',
            field=models.CharField(max_length=100),
        ),
    ]
